variable "project_id" {
  type        = string
  description = "(Required) Target Project identifier provided by the customer"
}

variable "is_organizational" {
  description = "(Optional) Set this field to 'true' to deploy secure-for-cloud to a GCP Organization."
  type        = bool
  default     = false
}

variable "organization_domain" {
  type        = string
  description = "(Optional) Organization domain. e.g. sysdig.com"
  default     = ""
}

variable "suffix" {
  type        = string
  description = "Suffix to uniquely identify resources during multiple installs. If not provided, random value is autogenerated"
  default     = null
}

variable "include_folders" {
  description = "(Optional) folders to include for organization in the format '[{folder_id_one}, {folder_id_two}]' i.e: '[\"123456789012\", \"123456789012\"]'"
  type        = set(string)
  default     = []
}

variable "exclude_folders" {
  description = "(Optional) folders to exclude for organization in the format '[{folder_id_one}, {folder_id_two}]' i.e: '[\"123456789012\", \"123456789012\"]'"
  type        = set(string)
  default     = []
}

variable "include_projects" {
  description = "(Optional) projects id to include for organization i.e: my-project-id"
  type        = set(string)
  default     = []
}

variable "exclude_projects" {
  description = "(Optional) projects id to exclude for organization i.e: my-project-id"
  type        = set(string)
  default     = []
}

variable "enable_automatic_onboarding" {
  type        = bool
  default     = false
  description = "true/false whether Sysdig should automatically discover latest set of accounts in onboarded organization or not"
}
