variable "project_id" {
  type        = string
  description = "(Required) Target Project identifier provided by the customer"
}

variable "labels" {
  type        = map(string)
  description = "(Optional) Labels to be associated with Sysdig-originated resources"
  default = {
    originator = "sysdig"
  }
}

variable "is_organizational" {
  description = "(Optional) Set this field to 'true' to deploy secure-for-cloud to a GCP Organization."
  type        = bool
  default     = false
}

variable "organization_domain" {
  type        = string
  description = "(Optional) Organization domain. e.g. sysdig.com"
  default     = ""
}

variable "external_id" {
  type        = string
  description = "(Required) Random string generated unique to a customer"
}

variable "suffix" {
  type        = string
  description = "Suffix to uniquely identify resources during multiple installs. If not provided, random value is autogenerated"
  default     = null
}