variable "project_id" {
  type        = string
  description = "(Required) Target Project identifier provided by the customer"
}

variable "is_organizational" {
  description = "(Optional) Set this field to 'true' to deploy secure-for-cloud to a GCP Organization."
  type        = bool
  default     = false
}

variable "organization_domain" {
  type        = string
  description = "(Optional) Organization domain. e.g. sysdig.com"
  default     = ""
}

variable "suffix" {
  type        = string
  description = "Suffix to uniquely identify resources during multiple installs. If not provided, random value is autogenerated"
  default     = null
}

variable "sysdig_secure_account_id" {
  type        = string
  description = "ID of the Sysdig Cloud Account to enable Config Posture for (in case of organization, ID of the Sysdig management account)"
}

variable "include_folders" {
  description = "(Optional) folders to include for organization"
  type        = set(string)
  default     = []
}

variable "exclude_folders" {
  description = "(Optional) folders to exclude for organization"
  type        = set(string)
  default     = []
}

variable "include_projects" {
  description = "(Optional) projects to include for organization"
  type        = set(string)
  default     = []
}

variable "exclude_projects" {
  description = "(Optional) projects to exclude for organization"
  type        = set(string)
  default     = []
}