variable "project_id" {
  type        = string
  description = "(Required) Target Project identifier provided by the customer"
}

variable "is_organizational" {
  description = "(Optional) Set this field to 'true' to deploy secure-for-cloud to a GCP Organization."
  type        = bool
  default     = false
}

variable "organization_domain" {
  type        = string
  description = "(Optional) Organization domain. e.g. sysdig.com"
  default     = ""
}

variable "suffix" {
  type        = string
  description = "Suffix to uniquely identify resources during multiple installs. If not provided, random value is autogenerated"
  default     = null
}

variable "sysdig_secure_account_id" {
  type        = string
  description = "ID of the Sysdig Cloud Account to enable Config Posture for (in case of organization, ID of the Sysdig management account)"
}

variable "wait_for_component_seconds" {
  type        = number
  description = "(Optional) Delay in seconds to wait after component operations (create/destroy) to ensure Sysdig backend has fully processed changes before proceeding. Set to 0 to disable."
  default     = 30
}
