# mandatory
variable "project_id" {
  type        = string
  description = "GCP Project ID"
}

variable "worker_identity" {
  type        = string
  description = "Sysdig provided Identity for the Service Account in charge of performing the host disk analysis"
}

# mandatory; one of  `sysdig_backend` or `sysdig_account_id`
variable "sysdig_backend" {
  type        = string
  description = "Sysdig provided AWS Account designated for the host scan.<br/>One of `sysdig_backend` or `sysdig_account_id`must be provided"
  default     = null
}

variable "sysdig_account_id" {
  type        = string
  description = "Sysdig provided GCP Account designated for the host scan.<br/>One of `sysdig_backend` or `sysdig_account_id`must be provided"
  default     = null
}

# optional
variable "role_name" {
  type        = string
  description = "Optional. Name for Sysdig operations on discovery and scan"
  default     = "SysdigCloudVM"
}



variable "suffix" {
  type        = string
  description = "Optional. Suffix word to enable multiple deployments with different naming<br/>(Workload Identity Pool and Providers have a soft deletion on Google Platform that will disallow name re-utilization)<br/>By default a random value will be autogenerated."
  default     = null
}

variable "is_organizational" {
  description = "Optional. Determines whether module must scope whole organization. Otherwise single project will be scoped"
  type        = bool
  default     = false
}

variable "organization_domain" {
  type        = string
  description = "Optional. If `is_organizational=true` is set, its mandatory to specify this value, with the GCP Organization domain. e.g. sysdig.com"
  default     = null
}